[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[hostname]
ssh_only = false
format = "[\\[$hostname\\]]($style) "

[directory]
read_only = " ro"
truncation_length = 2
truncation_symbol = ".../"
truncate_to_repo = false

[git_branch]
symbol = ""

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[container]
disabled = true

[docker_context]
disabled = true

[gcloud]
symbol = "gcp "

[kubernetes]
format = '[$context\($namespace\)](green) '
disabled = false

[package]
disabled = true

[python]
format = '[${pyenv_prefix}$virtualenv ]($style)'

[nodejs]
symbol = "nodejs "

[rust]
symbol = "rs "

[golang]
symbol = "go "

[nix_shell]
symbol = "nix "
